### ISSUE TITLE
Migrate to PostgreSQL

### ISSUE THREAD

**Issue by kbuffardi** [ChicoState/PantryNode#23] opened 2023-02-20 05:00 UTC
- [ ] Replace MongoDB with PostgreSQL

**Comment by MMurtey** [comment] 2023-02-28 18:11
https://sequelize.org/ might be worth looking into as a PostgreSQL-compatible ORM; not quite a drop-in replacement, but at least similar "form."

**Comment by briswells** [comment] 2023-02-28 18:18
It appears that the database is offline. I think this issue should be renamed, re-create the data.

**Comment by MMurtey** [comment] 2023-02-28 18:32
Branch for this issue created: 'migrate-to-postgresql'

One of the first things we should is create a Dockerfile for a PostgreSQL container that we can work with as we build this out. We'll give the "Containerize" team a heds-up.

**Comment by briswells** [comment] 2023-03-01 02:59
Since MongoDB was documents based we will need to create a new scheme for the tables.

**Comment by kbuffardi** [comment] 2023-03-01 04:48
@briswells right. If you want a peek at how they (at least intended) the relationships to be, take a look at [this diagram](../blob/main/docs/new.jpeg)

**Comment by hamsaraj7106** [comment] 2023-03-01 07:02
Since MongoDB data is in JSON format, to export it, we will need to transform it into a tabular structure with rows and columns.

**Comment by kbuffardi** [comment] 2023-03-01 17:08
There is no useful data currently, if there's anything in the database, it is just dummy data they used to test the site. Only the schema needs to be translated into a relational db for postgres

**Comment by briswells** [comment] 2023-03-01 19:35
I may have gone a little overboard but I created a ER diagram that can handle not only everything the old database could but extremely expanded functionality. 

Donations, thrown out food, and "purchases" are handled in a single table transactions. Each transaction will have line items sorted by item and expiration date. Meaning if you donate 2 of the same item that expire at different times they will be 2 different entries in the 'trans_item'  table, but will link to a single entry in the 'item' table. The idea behind this is you can locate any item, even if you have multiple buildings based on when it was received/when they expire. This lets us run reports for expiring food etc.

You also may notice that there is no inventory table. Inventory will be tracked with a materialized view which will refresh each time a transaction is made. I've done my best to put the DB in 3NF but wasn't super careful so I may have missed something.

The main place I deviated from standard crow's feet ER diagraming is underlining required values. Let me know what you all think. I know it's a lot more than the previous DB but why not plan for the future.  

![Foodbank ER Diagram](https://user-images.githubusercontent.com/32494875/222239840-49cb80da-86b9-4a74-884f-b509f9bda449.png)

**Comment by SANDESHSOBARAD** [comment] 2023-03-01 21:22
The ER diagram looks great and I think it's a great idea to keep in mind about the future enhancements, I think it's totally doable, as of now since there is no actual data I think we can start from scratch and build with the better ideas you presented in the ER diagram. I liked what you did with the items expiry part.

**Comment by MMurtey** [comment] 2023-03-04 18:05
I've been reading through the documentation for Sequelize (MIT-licensed, stable @v6) and I think it'll make our lives easier - operations are similar to Mongoose (no need to reinvent the wheel). I'm going to start playing with an implementation and unless there are any objections, I say we roll with it.

**Comment by MMurtey** [comment] 2023-03-04 21:22
Branched this feature branch to another branch to demonstrate("implement-sequelize") - it was easy enough. If you pull it, rerun npm install and run /bin/db_test directly.

**Comment by briswells** [comment] 2023-03-06 16:54
I may be missing something but I'm a little confused about the use case for sequalize. I can only see documentation for making table creation and queries slightly easier but it doesn't seem to allow for robust database features. Am I missing something?

**Comment by MMurtey** [comment] 2023-03-06 17:44
What sort of advanced database features do you have in mind? 

My understanding is that this is a basic CRUD application. We could write queries by hand; make functions to handle common queries and parse parameters... But, the Sequelize (ORM) here is serving the same function as Mongoose (ODM) in the application's current state. And, because everything's an object, this makes for as close to a "drop-in" replacement as we might get. The way I see it, we could just define the models and run through the few files doing logic and swap out methods/parameters (making updates to the logic if needed). 

I'd like to be as efficient as possible in this conversion. I've no problem taking the long way around if we need to; I just want to make sure we _need_ to.

**Comment by briswells** [comment] 2023-03-07 01:01
So it turns out I was looking at the wrong documentation, and there's a lot more than I originally thought, but even after I found the proper documentation there was still a massive issue. Sequalize doesn't support materialized views natively. I did find a [module ](https://www.npmjs.com/package/sequelize-mv-support) that adds support but I'm hesitant to use it. I have a few other concerns as well, but this seems like a big picture question so I thinking talking as a team would be easier.

**Comment by briswells** [comment] 2023-03-11 03:14
The branch is now in a semi stable state. We can register and login. My next is to create an sudo model for inventory. I'm still figuring out the best way to implement it since sequelize doesn't work with views. If people are able to jump in and start updating the route functions with with new models that'd be awesome.

**Comment by AbhinavReddy-Dev** [comment] 2023-03-11 20:27
> The branch is now in a semi stable state. We can register and login. My next is to create an sudo model for inventory. I'm still figuring out the best way to implement it since sequelize doesn't work with views. If people are able to jump in and start updating the route functions with with new models that'd be awesome.

Can you please guide me on running it in my local? I have tried it on implement-sequelize branch and there seems to be a problem `Error: Cannot find module '../models-test/init-models'`.

**Comment by briswells** [comment] 2023-03-11 20:35
> > The branch is now in a semi stable state. We can register and login. My next is to create an sudo model for inventory. I'm still figuring out the best way to implement it since sequelize doesn't work with views. If people are able to jump in and start updating the route functions with with new models that'd be awesome.
> 
> Can you please guide me on running it in my local? I have tried it on implement-sequelize branch and there seems to be a problem `Error: Cannot find module '../models-test/init-models'`.

Are you following the updated README when attempting to run the program?

**Comment by Jooms** [comment] 2023-03-12 03:54
Sanity check and a question.

----

I checked out `migrate-to-postgresql` (which seems to be the branch you are referring to as "semi stable").

I set the missing variables in `docker-compose.yml`,  and was able to get the DB running using docker-compose!

Proof
```
docker-compose up
time="2023-03-11T19:37:35-08:00" level=warning msg="Found orphan containers ([node database]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."
[+] Running 2/0
 - Container pantrynode-db_sandbox-1  Created                                                                                                                                                                                        0.0s  - Container pantrynode-db_admin-1    Created                                                                                                                                                                                        0.0s Attaching to pantrynode-db_admin-1, pantrynode-db_sandbox-1
pantrynode-db_sandbox-1  | The files belonging to this database system will be owned by user "postgres".
pantrynode-db_sandbox-1  | This user must also own the server process.
pantrynode-db_sandbox-1  |
pantrynode-db_sandbox-1  | The database cluster will be initialized with locale "en_US.utf8".
pantrynode-db_sandbox-1  | The default database encoding has accordingly been set to "UTF8".
pantrynode-db_sandbox-1  | The default text search configuration will be set to "english".
pantrynode-db_sandbox-1  |
pantrynode-db_sandbox-1  | Data page checksums are disabled.
pantrynode-db_sandbox-1  |
pantrynode-db_sandbox-1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
pantrynode-db_sandbox-1  | creating subdirectories ... ok
pantrynode-db_sandbox-1  | selecting dynamic shared memory implementation ... posix
pantrynode-db_sandbox-1  | selecting default max_connections ... 100
pantrynode-db_sandbox-1  | selecting default shared_buffers ... 128MB
pantrynode-db_sandbox-1  | selecting default time zone ... Etc/UTC
pantrynode-db_sandbox-1  | creating configuration files ... ok
pantrynode-db_sandbox-1  | running bootstrap script ... ok
pantrynode-db_admin-1    | [2023-03-12 03:37:40 +0000] [1] [INFO] Starting gunicorn 20.1.0
pantrynode-db_admin-1    | [2023-03-12 03:37:40 +0000] [1] [INFO] Listening at: http://[::]:80 (1)
pantrynode-db_admin-1    | [2023-03-12 03:37:40 +0000] [1] [INFO] Using worker: gthread
pantrynode-db_admin-1    | [2023-03-12 03:37:40 +0000] [81] [INFO] Booting worker with pid: 81
pantrynode-db_sandbox-1  | performing post-bootstrap initialization ... ok
pantrynode-db_sandbox-1  | syncing data to disk ... ok
pantrynode-db_sandbox-1  |
pantrynode-db_sandbox-1  |
pantrynode-db_sandbox-1  | Success. You can now start the database server using:
pantrynode-db_sandbox-1  |
pantrynode-db_sandbox-1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
pantrynode-db_sandbox-1  |
pantrynode-db_sandbox-1  | initdb: warning: enabling "trust" authentication for local connections
pantrynode-db_sandbox-1  | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
pantrynode-db_sandbox-1  | waiting for server to start....2023-03-12 03:37:50.775 UTC [49] LOG:  starting PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
pantrynode-db_sandbox-1  | 2023-03-12 03:37:50.777 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
pantrynode-db_sandbox-1  | 2023-03-12 03:37:50.879 UTC [52] LOG:  database system was shut down at 2023-03-12 03:37:41 UTC
pantrynode-db_sandbox-1  | 2023-03-12 03:37:50.929 UTC [49] LOG:  database system is ready to accept connections
pantrynode-db_sandbox-1  |  done
pantrynode-db_sandbox-1  | server started
pantrynode-db_sandbox-1  | CREATE DATABASE
pantrynode-db_sandbox-1  |
pantrynode-db_sandbox-1  |
pantrynode-db_sandbox-1  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/create_tables.sql
pantrynode-db_sandbox-1  | CREATE TABLE
pantrynode-db_sandbox-1  | CREATE TABLE
pantrynode-db_sandbox-1  | CREATE TABLE
pantrynode-db_sandbox-1  | CREATE TABLE
pantrynode-db_sandbox-1  | CREATE TABLE
pantrynode-db_sandbox-1  | CREATE TYPE
pantrynode-db_sandbox-1  | CREATE TABLE
pantrynode-db_sandbox-1  | CREATE TABLE
pantrynode-db_sandbox-1  | CREATE TYPE
pantrynode-db_sandbox-1  | CREATE TABLE
pantrynode-db_sandbox-1  | CREATE TABLE
pantrynode-db_sandbox-1  | CREATE TABLE
pantrynode-db_sandbox-1  | CREATE TABLE
pantrynode-db_sandbox-1  | CREATE TABLE
pantrynode-db_sandbox-1  | CREATE TYPE
pantrynode-db_sandbox-1  | CREATE TABLE
pantrynode-db_sandbox-1  | ALTER TABLE
pantrynode-db_sandbox-1  | ALTER TABLE
pantrynode-db_sandbox-1  |
pantrynode-db_sandbox-1  |
pantrynode-db_sandbox-1  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/dummy_data.sql
pantrynode-db_sandbox-1  | INSERT 0 3
pantrynode-db_sandbox-1  | INSERT 0 1
pantrynode-db_sandbox-1  | INSERT 0 1
pantrynode-db_sandbox-1  | UPDATE 1
pantrynode-db_sandbox-1  | INSERT 0 1
pantrynode-db_sandbox-1  | INSERT 0 1
pantrynode-db_sandbox-1  | UPDATE 1
pantrynode-db_sandbox-1  | INSERT 0 1
pantrynode-db_sandbox-1  | INSERT 0 1
pantrynode-db_sandbox-1  | INSERT 0 1
pantrynode-db_sandbox-1  | INSERT 0 2
pantrynode-db_sandbox-1  | INSERT 0 4
pantrynode-db_sandbox-1  | INSERT 0 1
pantrynode-db_sandbox-1  | INSERT 0 2
pantrynode-db_sandbox-1  | INSERT 0 4
pantrynode-db_sandbox-1  | INSERT 0 4
pantrynode-db_sandbox-1  | INSERT 0 2
pantrynode-db_sandbox-1  | INSERT 0 1
pantrynode-db_sandbox-1  | UPDATE 1
pantrynode-db_sandbox-1  | INSERT 0 1
pantrynode-db_sandbox-1  | INSERT 0 2
pantrynode-db_sandbox-1  | INSERT 0 2
pantrynode-db_sandbox-1  |
pantrynode-db_sandbox-1  |
pantrynode-db_sandbox-1  | waiting for server to shut down...2023-03-12 03:37:53.908 UTC [49] LOG:  received fast shutdown request
pantrynode-db_sandbox-1  | .2023-03-12 03:37:53.953 UTC [49] LOG:  aborting any active transactions
pantrynode-db_sandbox-1  | 2023-03-12 03:37:53.955 UTC [49] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
pantrynode-db_sandbox-1  | 2023-03-12 03:37:53.955 UTC [50] LOG:  shutting down
pantrynode-db_sandbox-1  | 2023-03-12 03:37:53.979 UTC [50] LOG:  checkpoint starting: shutdown immediate
pantrynode-db_sandbox-1  | ......2023-03-12 03:38:00.196 UTC [50] LOG:  checkpoint complete: wrote 1007 buffers (6.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.181 s, sync=5.953 s, total=6.241 s; sync files=297, longest=0.055 s, average=0.021 s; distance=4539 kB, estimate=4539 kB
pantrynode-db_sandbox-1  | 2023-03-12 03:38:00.333 UTC [49] LOG:  database system is shut down
pantrynode-db_sandbox-1  |  done
pantrynode-db_sandbox-1  | server stopped
pantrynode-db_sandbox-1  |
pantrynode-db_sandbox-1  | PostgreSQL init process complete; ready for start up.
pantrynode-db_sandbox-1  |
pantrynode-db_sandbox-1  | 2023-03-12 03:38:00.490 UTC [1] LOG:  starting PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
pantrynode-db_sandbox-1  | 2023-03-12 03:38:00.491 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
pantrynode-db_sandbox-1  | 2023-03-12 03:38:00.491 UTC [1] LOG:  listening on IPv6 address "::", port 5432
pantrynode-db_sandbox-1  | 2023-03-12 03:38:00.520 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
pantrynode-db_sandbox-1  | 2023-03-12 03:38:00.585 UTC [69] LOG:  database system was shut down at 2023-03-12 03:38:00 UTC
pantrynode-db_sandbox-1  | 2023-03-12 03:38:00.637 UTC [1] LOG:  database system is ready to accept connections
```

Looks like the dummy data load works as well.

------

@briswells 

Anything I can help with? I don't want to jump in if it makes it more chaotic.

> If people are able to jump in and start updating the route functions with with new models that'd be awesome.

You got one in mind for me to split off? Do you already have a commit that connects the app to the db?

**Comment by briswells** [comment] 2023-03-12 17:29
> 

Totally our fault, poor branch management. The most up to date branch is implement-sequelize, but as it looks like we're going with sequelize for sure, at some point today I will be merging it back into the issue branch of migrate to postgres. Right now /home is half converted but I did a rush job so we could at least login. Everything in config and the user routes are good. The main place the needs work is sales. If you wanted to start on either /home or /add_stock you should have all the models as others may require the inventory model I'm working on (stock, but the way they used stock is more like how we use transaction). There are examples on how to use sequelize in the code and the most up to date DB schema in the docs folder, but let me know if you have any questions.

**Comment by AbhinavReddy-Dev** [comment] 2023-03-13 01:56
> > 
> 
> @Jooms Totally our fault, poor branch management. The most up to date branch is implement-sequelize, but as it looks like we're going with sequelize for sure, at some point today I will be merging it back into the issue branch of migrate to postgres. Right now /home is half converted but I did a rush job so we could at least login. Everything in config and the user routes are good. The main place the needs work is sales. If you wanted to start on either /home or /add_stock you should have all the models as others may require the inventory model I'm working on (stock, but the way they used stock is more like how we use transaction). There are examples on how to use sequelize in the code and the most up to date DB schema in the docs folder, but let me know if you have any questions.

One thing we can do to avoid mongo errors is to comment out everything related to mongo, schema and APIs except signup and login functionality on back-end. After this merge we can start working on implementing APIs. Any thoughts on this approach?

**Comment by briswells** [comment] 2023-03-13 03:18
> > > 
> > 
> > 
> > @Jooms Totally our fault, poor branch management. The most up to date branch is implement-sequelize, but as it looks like we're going with sequelize for sure, at some point today I will be merging it back into the issue branch of migrate to postgres. Right now /home is half converted but I did a rush job so we could at least login. Everything in config and the user routes are good. The main place the needs work is sales. If you wanted to start on either /home or /add_stock you should have all the models as others may require the inventory model I'm working on (stock, but the way they used stock is more like how we use transaction). There are examples on how to use sequelize in the code and the most up to date DB schema in the docs folder, but let me know if you have any questions.
> 
> One thing we can do to avoid mongo errors is to comment out everything related to mongo, schema and APIs except signup and login functionality on back-end. After this merge we can start working on implementing APIs. Any thoughts on this approach?

I just merged everything into migrate-to-postgresql so you now should be able to run the site using the updated README. If you use any routes that aren't implemented it will crash but besides that I haven't had any issues. I've kept the import statements to the old models just so we know what was being used when rewriting routes. Mongoose is only being used in the old model files right now and removing that isn't going to stop crashes so I've left them in and think we can remove them when the models are officially migrated.

**Comment by briswells** [comment] 2023-03-13 03:20
On a side note now the changes from implement-sequelize are merged into migrate-to-postgresql is anyone opposed to **deleting** that branch? If you have unstaged changes you want to save I'd suggest either pushing then merging them, or stashing them and applying the stash to migrate-to-postgresql.

**Comment by Jooms** [comment] 2023-03-13 06:20
Oh, well if it's mostly functional, I'm starting to lean with @AbhinavReddy-Dev. @briswells can you create a pull request as-is? (I'd create one but I want you to be the PR author)

It looks like you've done a *ton* of awesome work. It would be great if that gets in so the frontend people can start benefiting from all the foundational chunks you've built out.

We can chat on the PR about what parts should be left for more PRs, and what we can get in with your first swing at it. Then divvy up the work from there.

---

Normally I'd rather we fix stuff without introducing regressions (turning off features / pages / etc). However, since this app currently *does not run*, and is hard to get running with MongoDB locally. Having anything running on postgres (even with fully-commented-out APIs or files) is a dramatic improvement.

**Comment by AbhinavReddy-Dev** [comment] 2023-03-13 10:04
> Oh, well if it's mostly functional, I'm starting to lean with @AbhinavReddy-Dev. @briswells can you create a pull request as-is? (I'd create one but I want you to be the PR author)
> 
> It looks like you've done a _ton_ of awesome work. It would be great if that gets in so the frontend people can start benefiting from all the foundational chunks you've built out.
> 
> We can chat on the PR about what parts should be left for more PRs, and what we can get in with your first swing at it. Then divvy up the work from there.
> 
> Normally I'd rather we fix stuff without introducing regressions (turning off features / pages / etc). However, since this app currently _does not run_, and is hard to get running with MongoDB locally. Having anything running on postgres (even with fully-commented-out APIs or files) is a dramatic improvement.

Yes, the inability to run mongo successfully in local made me think about not working on containerize it would save time.

**Comment by briswells** [comment] 2023-03-13 15:54
> a

Sounds good. I'll be open a pull request here soon. I'm guessing the linter will go crazy when I do, I'll clean up what it finds and update the PW.

**Comment by briswells** [comment] 2023-03-20 15:54
I am waiting for a 2nd code review to merge postgressql-migration into main. I have created a new branch 'route-conversion' in the mean time so I can continue to commit without messing with the pull request. I am unsure if I should merge that into postgressql-migration after the pull request is accepted or continue to work on 'route-conversion' as this work is a bit tangential to migrating to postgres.

**Comment by Jooms** [comment] 2023-03-20 16:21
Approved, please merge @briswells 
https://github.com/ChicoState/PantryNode/pull/57

**Comment by MMurtey** [comment] 2023-03-20 17:44
@briswells Can we meet/talk to discuss a division of labor on converting routes?

**Closed** 2023-03-20 18:07 UTC
Labels: dependencies

**Comment by briswells** [comment] 2023-03-20 18:29
> @briswells Can we meet/talk to discuss a division of labor on converting routes?

If we don't have time tomorrow in class, we can try and schedule a meeting for a different time. Looks like the project bot closed this issue so lets move all future discussion to #61 as it seems more appropriate since technically we have migrated to Postgres.
